### ISSUE TITLE
Application error on first login after setting up OAuth

### ISSUE THREAD

**Issue by ajyoon** [recursecenter/blaggregator#132]
My first time logging into the blaggregator site leads to a dead-end Application error after granting OAuth access. The erroring page is `https://blaggregator.recurse.com/complete/hackerschool/?code=......`

"Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. "

(If you do actually want to check out the error log, I made the last request at 7:07AM EST)

**Comment by punchagan** [comment]
Did it work after the first time?

**Comment by ajyoon** [comment]
No, https://blaggregator.recurse.com/ redirects to https://blaggregator.recurse.com/login/?next=/new/ where I'm asked to log in with RC OAuth. After clicking I no longer have to go to RC to log in (cookie stored I guess?) and it redirects me back to the erroring page.

**Comment by punchagan** [comment]
@ajyoon Thanks for the report.  Sorry that it took so long to fix, but, should hopefully be fixed now!
