### ISSUE TITLE
Tag authors in the zulip stream

### ISSUE THREAD

**Issue by heatherbooker** [recursecenter/blaggregator#165]
It seems like right now, the bot posts the authors name in bold when a new post goes up and is posted to zulip.

It would be cool if instead, the bot tagged the author, so they are automagically subscribed to the stream and see all the loving and curious comments that they get :heart_eyes:

**Comment by punchagan** [comment]
@heatherbooker Thanks for the suggestion! I don't know if there is a nice way to link the Recurse account to the Zulip account. We could use the email, but not sure if that's a reliable way of doing this. We could at least change the bold name to a "silent mention". 

@davidbalbert Is there a nice way of figuring out the Zulip username if I know a person's RC API ID?

**Comment by nickdrozd** [comment]
I was going to come and suggest that authors' Zulip avatars should also be used for their blog threads, bu I guess that would be blocked by the same problem.

So if anyone manages to get this working, please add avatars while you're at it!

**Comment by davidbalbert** [comment]
@punchagan I just realized I missed this ping from you 1.5 years ago 😰 . My apologies!

The good news is yes! You can go from RC ID to Zulip ID. The profile endpoint (https://www.recurse.com/api/v1/profiles/:id) includes a `zulip_id` key that should work. There's no guarantee that everyone has this set (it's either a manual process or a best effort automatic one, I forget which), but 98% of all Recursers have it set.

For an easy test to see what the data looks like, log in to recurse.com and then load https://www.recurse.com/api/v1/profiles/me

**Comment by punchagan** [comment]
> @punchagan I just realized I missed this ping from you 1.5 years ago cold_sweat . My apologies!

No worries, @davidbalbert. :)  

Thanks for bumping this up, @nickdrozd !

> The good news is yes! You can go from RC ID to Zulip ID. The profile endpoint (https://www.recurse.com/api/v1/profiles/:id) includes a `zulip_id` key that should work. There's no guarantee that everyone has this set (it's either a manual process or a best effort automatic one, I forget which), but 98% of all Recursers have it set.

This is great! I'll look into trying to use this to make the blaggregator bot be smarter. :)

Also, I'll look at how this Zulip ID is added to the recurse.com API data, and may be document it on Blaggregator docs to make it easy for new Recursers to set this up.

**Comment by punchagan** [comment]
> I was going to come and suggest that authors' Zulip avatars should also be used for their blog threads, bu I guess that would be blocked by the same problem.

@nickdrozd I looked at the zulip API docs to see if the avatar can be changed for a message, and couldn't find anything. If you know that this is possible, could you link to some documentation/examples? Thanks!

**Comment by punchagan** [comment]
>  There's no guarantee that everyone has this set (it's either a manual process or a best effort automatic one, I forget which), but 98% of all Recursers have it set.

@davidbalbert could you check and let me know how the Zulip IDs are set in the RC API? This would be something useful to add in the README for new recursers who may run into an issue with their post announcements not mentioning them.

**Comment by nickdrozd** [comment]
> I looked at the zulip API docs to see if the avatar can be changed for a message, and couldn't find anything. If you know that this is possible, could you link to some documentation/examples? Thanks!

I was just assuming that it would be possible, but I have no idea if it is, or how to do it.

**Comment by davidbalbert** [comment]
@punchagan we import people's Zulip IDs once per batch once everyone has signed up for Zulip. It's a semi-manual process: first we automatically match up anyone who uses the same email address on recurse.com and Zulip. Then for anyone we weren't able to match automatically, we match people manually.
