### ISSUE TITLE
Atom feed doesn't work?

### ISSUE THREAD

**Issue by icco** [recursecenter/blaggregator#167]
```
{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet"}
```

I get the above error message when I visit https://blaggregator.recurse.com/atom.xml?token=xxxxxxxx, linked from the footer of the blaggregator homepage while logged in.

**Comment by punchagan** [comment]
Thanks for the report, @icco 
I couldn't reproduce it myself. Could you generate a new token from the profile page and see if that changes anything?

**Comment by icco** [comment]
that fixed it!
